### PR TITLE
Add search index

### PR DESCRIPTION
**Pull request by travisbeckham**
Add search index for 2.15 docs

### CODE REVIEW

**Comment by wmorgan** [comment]
So this will create a JSON file designed for programmatic search engine consumption, correct? Do we need to mark this as noindex or anything like that so that it doesn't appear in e.g. Google search results?

**Comment by travisbeckham** [comment]
> So this will create a JSON file designed for programmatic search engine consumption, correct? Do we need to mark this as noindex or anything like that so that it doesn't appear in e.g. Google search results?

Good point. We could add a robots.txt file, but that might be ignored. Seems like the best way to deal with this is to add a header from the web server. Something like:

```
location ~* \.(json)$ {
 add_header X-Robots-Tag "noindex";
}
```

...but I'm a bit fuzzy on how the linkerd docs site actually get served. Want to just start with a robots file?

**Comment by travisbeckham** [comment]
On a related question, we're currently generating these json files for every section of the site. Do you know what they are for? SEO? https://linkerd.io/2.15/index.json

If so, this search index is overriding it. Let me rework this, so the search index get dumped in the root.

**Comment by wmorgan** [comment]
I am not sure what those files are... maybe some Hugo artifact? At any rate, there is already a robots.txt so the easiest approach is to just add a line there.

**Comment by travisbeckham** [comment]
Those json files are intentionally built, not a Hugo artifact, so I'll avoid clobbering them. I'll assume something reads them.

I've added the search index to robots.txt and moved it to the root.

**Comment by travisbeckham** [comment]
Ok, I think it ready for your review again.

I also fixed some deprecated function calls, and bumped the Hugo version.

**Review by wmorgan — APPROVED** [review]

**Pull request merged**
