### PR TITLE
feat(ci): add markdown seo check

### PR DESCRIPTION
**Pull request by PatrickHeneise**
Signed-off-by: Patrick Heneise <patrick@zentered.co>

### CODE REVIEW

**Review by cpretzer — COMMENTED** [review]
@PatrickHeneise do we have to merge this first before seeing it run? I don't see the `Validate generated HTML` test run on this PR

Or does it only run when an HTML generated page is changed?

**Comment by PatrickHeneise** [comment]
there's a condition on the check:

```
on:
  pull_request:
    paths:
      - linkerd.io/**
```

So this won't run until it's merged and changes are made on the website.

**Review by cpretzer — APPROVED** [review]
LGTM

**Comment by cpretzer** [comment]
> there's a condition on the check:
> 
> ```
> on:
>   pull_request:
>     paths:
>       - linkerd.io/**
> ```
> 
> So this won't run until it's merged and changes are made on the website. Also, this doesn't check existing files, only modified ones in a PR.

Thanks for confiming @PatrickHeneise

**Pull request merged**
