### PR TITLE
Website updates

### PR DESCRIPTION
**Pull request by PatrickHeneise**
- fix json schema
- add meetup-in-a-box page
- implement design feedback

@PaulMichaelArmstrong

### CODE REVIEW

**Comment by PaulMichaelArmstrong** [comment]
Can we make it so the links in the first section are stacked and have the whole width so they don't wrap, please?

Screen Shot 2020-12-09 at 9 22 34 AM
Screen Shot 2020-12-09 at 9 23 19 AM
Screen Shot 2020-12-09 at 9 24 03 AM

**Comment by PaulMichaelArmstrong** [comment]
It also looks like we lost any padding around the icons in the sections.

Screen Shot 2020-12-09 at 9 27 28 AM

**Comment by PatrickHeneise** [comment]
Something went wrong there, sorry. Will review and fix in the morning.

**Review by PaulMichaelArmstrong — APPROVED** [review]

**Review by cpretzer — APPROVED** [review]
Tested locally and on netlify, layouts look correct

**Comment by cpretzer** [comment]
@PatrickHeneise there are some conflicts with the base branch, would you mind rebasing and pushing again? I'll get this change through once the conflicts are resolved

FYI @PaulMichaelArmstrong

**Comment by PatrickHeneise** [comment]
@cpretzer thanks! I updated the branch, but don't see any conflicts.

**Comment by cpretzer** [comment]
Thanks @PatrickHeneise I can merge it now, so whatever you did worked :+1:

**Pull request merged**
