### PR TITLE
2.6 release docs

### PR DESCRIPTION
**Pull request by grampelberg**

### CODE REVIEW

**Comment by ihcsim** [comment]
The DCO failure is caused by the older 54a41d75969d3b25257b388b260b7c65d67e0831 commit, during merge. A force push will probably mess up the newer commits. Feel free to squash this PR.

**Comment by grampelberg** [comment]
@ihcsim should we mention the proxy-injector label change in the upgrade docs?

**Comment by ihcsim** [comment]
It's already included in the 2.6 upgrade notes in this PR. The new `config.linkerd.io/admission-webhooks: disabled` label for `kube-system` namespace, right?

**Comment by grampelberg** [comment]
Yup, that's it. I swear I can read!

**Pull request merged**
