### PR TITLE
Add service mesh glossary page

### PR DESCRIPTION
**Pull request by C-Mejlak**
Screenshot from 2021-04-13 16-12-44

### CODE REVIEW

**Comment by PaulMichaelArmstrong** [comment]
@C-Mejlak We need the link-on-hover function for the terms.

**Comment by cpretzer** [comment]
@C-Mejlak some [lint checks](https://github.com/linkerd/website/pull/1037/checks?check_run_id=2334201636) are failing as well. 

I'm open to relaxing this check if it will not adversely affect the page layout for SEO

**Comment by C-Mejlak** [comment]
> @C-Mejlak We need the link-on-hover function for the terms.

@PaulMichaelArmstrong do you mean like the ones we have https://buoyant.io/linkerd-runbook/ ?

**Comment by PaulMichaelArmstrong** [comment]
@C-Mejlak, yes please.

**Comment by C-Mejlak** [comment]
@cpretzer fixed linting issues. Although it should have no impact on SEO or anything else, I don't think you should modify the linting rules.

This was just an oversight from my end, because I had soft wrap enabled
Thanks

**Comment by C-Mejlak** [comment]
@PaulMichaelArmstrong implemented the show icon on hover for docs headings.
Also as a user clicks, the URL changes, as discussed.

Would it make sense to copy automatically to the clipboard and show a toast notification to the user?

**Comment by cpretzer** [comment]
> @PaulMichaelArmstrong implemented the show icon on hover for docs headings.
> Also as a user clicks, the URL changes, as discussed.
> 
> Would it make sense to copy automatically to the clipboard and show a toast notification to the user?

That would be super cool, IMO. I know folks have asked for that functionality for code snippets, too.

**Review by cpretzer — APPROVED** [review]
The preview looks good and I'm seeing the hover anchors @PaulMichaelArmstrong

**Comment by PaulMichaelArmstrong** [comment]
Yeah. This looks good. Let's go ahead an merge this one and I'll put together something for the copy to clipboard and open a separate ticket for that.

Thanks @C-Mejlak and @cpretzer!

**Pull request merged**
