### PR TITLE
Feature ambassador

### PR DESCRIPTION
**Pull request by karr9**
styles and code are added to highlight an ambassador

### CODE REVIEW

**Comment by kflynn** [comment]
@karr9, muchas gracias! Lo único que prefiero sería que, en vez de aplicar los estilos basado en el nombre del embajador, podemos tener un attribute o algo así? Seguro que en el futuro tendrémos mas embajadores emiriti...

-- 

@karr9, many thanks! The only thing I'd like would be if we could have a flag or some such instead of applying the styling based on the name of the ambassador. I'm sure we'll have more ambassadors emeriti in the future...

**Comment by karr9** [comment]
> ..

ok, agregare un atributo nuevo y en base a ese se hará el highlight

**Comment by karr9** [comment]
@kflynn I have added a new property highlight: true or false, only with this is the change made to the card

**Review by kflynn — APPROVED** [review]
¡Gracias @karr9! me parece bien. 🙂

**Pull request merged**
