### PR TITLE
Fix broken link in Traffic Split page

### PR DESCRIPTION
**Pull request by gaiazov**
Signed-off-by: Leonid Gaiazov <leonid.gaiazov@appian.com>

The link to the `TrafficSplit API` is broken on https://linkerd.io/2/features/traffic-split/

Note that there are 4 versions of the `traffic-split.md` file - I chose the latest one
https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha1/traffic-split.md
https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha2/traffic-split.md
https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha3/traffic-split.md
https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha4/traffic-split.md

I also thought about linking to a specific SHA, which should be stable, but will get stale 🤔

### CODE REVIEW

**Review by cpretzer — COMMENTED** [review]
thanks for the fix @gaiazov 

Currently, linkerd supports `v1alpha1` (we're planning to support a more recent version), so what do you think of either linking to [v1alpha1](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha1/traffic-split.md), or to the entire [version list](https://github.com/servicemeshinterface/smi-spec/tree/master/apis/traffic-split) of the TrafficSplit spec?

**Review by cpretzer — CHANGES_REQUESTED** [review]
hi @gaiazov I think the right thing to do is link to the entire list of traffic split versions. Are you up for making this change so we can merge the PR?

**Comment by gaiazov** [comment]
@cpretzer done!

**Comment by cpretzer** [comment]
thanks @gaiazov

**Review by cpretzer — APPROVED** [review]
LGTM

**Pull request merged**
