### PR TITLE
Update Proxy Configuration reference for 2.10

### LINKED ISSUE #994: 2.10 proxy annotation docs don't include some 2.9 details
There's extra content about CSV for skip-*-ports options in here: https://linkerd.io/2.9/reference/proxy-configuration/

Somehow that did not make it here: https://linkerd.io/2.10/reference/proxy-configuration/

"Comma-separated list of values, where each value can be a port number or a range a-b."

### PR DESCRIPTION
**Pull request by alpeb**
Fixes #994

(Updates docs in accordance to linkerd/linkerd2#5906)

Reapplies #888, which should have been done as a `linkerd doc` amendment
first, and adds some missing annotations.

### CODE REVIEW

**Review by wmorgan — APPROVED** [review]
Thank you!

**Review by kleimkuhler — APPROVED** [review]
👍 also closes #993

**Comment by cpretzer** [comment]
@PatrickHeneise can you help to troubleshoot this error? https://github.com/linkerd/website/pull/996/checks?check_run_id=2125286934

I see a debug flag on the action, should we add that?

**Comment by wmorgan** [comment]
For now let's merge this. It's important to get this content out there for people who are upgrading to 2.10.

**Pull request merged**
