### PR TITLE
Support ARM CLI

### PR DESCRIPTION
**Pull request by aliariff**
# Changes
- Add checking the machine arch for an arm machine and download the correct binary file.

Merge before https://github.com/linkerd/linkerd2/pull/4841

### CODE REVIEW

**Comment by grampelberg** [comment]
Would you mind adding tests for these as well?

**Comment by aliariff** [comment]
The broken test is expected. The current release did not have an extra arch name in the release artifacts.
After #4841 merged and a new release tag is created, then this will pass.

**Comment by aliariff** [comment]
And adding a test for the arm machine, I don't think we can do that, because the script relies on `uname -m` which we cant stub.

**Comment by kleimkuhler** [comment]
@aliariff Just a heads up it looks like this needs to merge with the latest changes on master

**Pull request merged**
