### PR TITLE
Update Heroes Page

### PR DESCRIPTION
**Pull request by C-Mejlak**
Update hero section
image

Update heroes card
image

Closes https://github.com/BuoyantIO/website/issues/245

### CODE REVIEW

**Comment by PaulMichaelArmstrong** [comment]
@C-Mejlak This looks great! Would we be able to make the names of the heroes on the cares Roboto Medium? Thank you!

**Comment by C-Mejlak** [comment]
Sure @PaulMichaelArmstrong, updated it

**Comment by PaulMichaelArmstrong** [comment]
This looks great. Thank you, @C-Mejlak.

**Comment by PaulMichaelArmstrong** [comment]
@cpretzer This is approved - can you merge if things look good to you?

**Review by cpretzer — APPROVED** [review]
LGTM

**Pull request merged**
