### PR TITLE
fix: add linkerd-config-overrides to manifest

### PR DESCRIPTION
**Pull request by ekapratama93**
linked issue [#5263](https://github.com/linkerd/linkerd2/issues/5263)

### CODE REVIEW

**Comment by grampelberg** [comment]
@ekapratama93 would you mind taking care of [DCO](https://github.com/linkerd/website/pull/862/checks?check_run_id=1429079114)?

**Review by grampelberg — COMMENTED** [review]
If you could fix the [linting errors](https://github.com/linkerd/website/pull/862/checks?check_run_id=1429079340), this is ready to merge!

**Comment by ekapratama93** [comment]
Please kindly check @grampelberg

**Review by cpretzer — APPROVED** [review]
:+1:

**Pull request merged**
