### PR TITLE
Referenced Buoyant article on Emissary.

### PR DESCRIPTION
**Pull request by JasonMorgan**
Wanted to reference the Buoyant article on integrating with Emissary as it provides the same information with more detail.

This time using the correct branch ;)

### CODE REVIEW

**Comment by cpretzer** [comment]
Should we just update the doc with the content?

We should link to the Buoyant article, just like we do with other tutorials like flagger. Since Ambassador is changing to Emissary, it makes sense to update the entire section in the linkerd docs

**Comment by JasonMorgan** [comment]
I wouldn't change the name in the official docs yet. It looks like renaming Ambassador API Gateway to Emissary Ingress is going to be a WIP for awhile.

**Comment by cpretzer** [comment]
> I wouldn't change the name in the official docs yet. It looks like renaming Ambassador API Gateway to Emissary Ingress is going to be a WIP for awhile.

Gotcha, thanks for clarifying @JasonMorgan

**Review by cpretzer — APPROVED** [review]
LGTM nice work @JasonMorgan :shipit:

**Pull request merged**
