### PR TITLE
feat: homepage updates

### PR DESCRIPTION
**Pull request by PatrickHeneise**

### CODE REVIEW

**Comment by PaulMichaelArmstrong** [comment]
Here is the design feedback for this: https://www.figma.com/file/T1MzgE7OlPCkhjZsl05YCtN2/Linkerd-Website?node-id=727%3A1471

**Comment by PaulMichaelArmstrong** [comment]
Is there a way to size up the triangles a bit more so they show more outside of the video?
Screen Shot 2021-02-11 at 8 51 26 AM

Can we update the logos here?
[logos.zip](https://github.com/linkerd/website/files/5967038/logos.zip)
Screen Shot 2021-02-11 at 8 51 36 AM

And can we make "featured blogs" 18px, please?
Screen Shot 2021-02-11 at 8 51 46 AM

Thank you!

**Comment by C-Mejlak** [comment]
All updated

**Review by PaulMichaelArmstrong — APPROVED** [review]
Design looks good to me.
@cpretzer can you take a look and merge if we're good?

**Comment by cpretzer** [comment]
@C-Mejlak @PaulMichaelArmstrong there are a couple of checks that are failing and the branch needs to be rebased with master

**Pull request merged**
