### PR TITLE
Correct cert-manager resource documentation

### PR DESCRIPTION
**Pull request by gabriellemadden**
Signed-off-by: Gabrielle Madden <49839049+gabriellemadden@users.noreply.github.com>

### CODE REVIEW

**Comment by cpretzer** [comment]
@gabriellemadden thanks for the PR to clarify the docs.

Would you mind amending your commit to include the [DCO](https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#developer-certificate-of-origin), this is necessary as part of the contributing guidelines. 

Once the [check](https://github.com/linkerd/website/pull/895/checks?check_run_id=1691099330) is successful, we can merge this PR.

**Comment by gabriellemadden** [comment]
@cpretzer oops my bad. Thought I had the correct email. Should be good to go

**Review by cpretzer — APPROVED** [review]
thanks @gabriellemadden

**Comment by gabriellemadden** [comment]
@cpretzer did you mean to close this without merging?

**Comment by cpretzer** [comment]
sorry about that. I think I clicked the buttons too quickly

**Comment by gabriellemadden** [comment]
Thanks!

**Pull request merged**
