### PR TITLE
Updated TCP port reference in Linkerd docs

### PR DESCRIPTION
**Pull request by JasonMorgan**
In regard to @alpeb's request in [this PR](https://github.com/linkerd/linkerd2/pull/6138). I'm updating the docs to match.

### CODE REVIEW

**Comment by JasonMorgan** [comment]
Can't be merged until the Linkerd helm chart is updated.

**Comment by JasonMorgan** [comment]
To save myself some time: I authorized all the commits in this branch.

**Comment by cpretzer** [comment]
@JasonMorgan is this ready to merge? I haven't seen whether the helm chart changes have been made

**Review by kleimkuhler — APPROVED** [review]
Looks like there is some cleanup for this to merge but the helm chart has been updated in linkerd/linkerd2#6388

**Pull request merged**
