### PR TITLE
Homepage reordering

### PR DESCRIPTION
**Pull request by PatrickHeneise**
Reorder sections
image

Change adopter banner background colour to white
image

### CODE REVIEW

**Review by cpretzer — APPROVED** [review]
Looks good

**Comment by PaulMichaelArmstrong** [comment]
@cpretzer Could you take a look at these changes and merge if the code looks good? The Netlify preview looks good to me.

**Comment by cpretzer** [comment]
@PatrickHeneise would you mind reading the branch? I can't do it from my end

**Comment by PatrickHeneise** [comment]
@cpretzer done

**Comment by cpretzer** [comment]
@PatrickHeneise I've merged the changes #904 so I'm going to close this one.

**Pull request closed without merging**
