### PR TITLE
Adding a Support & Training page

### PR DESCRIPTION
**Pull request by nate-double-u**
First pass at adding a Support & Training page. This keeps the original look and feel of the Enterprise page, but adds sections for courses and commercial support.

* Removing enterprise page and replacing it with the new Support & Training page
* Adding redirect from enterprise -> support-training

Deploy preview: https://deploy-preview-1076--linkerdio.netlify.app/support-training/
Redirect check: 
- [x] https://deploy-preview-1076--linkerdio.netlify.app/enterprise

fixes: #1074

---
TODO:
- [x] Correct spacing around Linux Foundation logo
- [x] Find and add more training options
- [x] Double check page redirect format for linkerd.io (currently 404s because the rename from enterprise->support-training hasn't been merged into main)
- [x] Update _Offering Linkerd support_ CTA button to link to correct page for editing

### CODE REVIEW

**Comment by nate-double-u** [comment]
@caniszczyk, is this sort of what you're looking for? 
https://deploy-preview-1076--linkerdio.netlify.app/support-training/

I've kept the original enterprise page look and feel, but I can bring it closer in line with the https://prometheus.io/support-training/ page if you'd like.

**Comment by caniszczyk** [comment]
I'm all for this, cc: @olix0r

**Comment by olix0r** [comment]
lgtm! going to let someone more familiar with the website repo approve/merge, though :) @wmorgan @cpretzer

**Comment by nate-double-u** [comment]
I've done some searching, and I'm not finding any other courses - a lot of what Google is surfacing points back to the edx course I've already linked here.

**Comment by nate-double-u** [comment]
(last force push just updates the `description` in the support-training.md file)

**Comment by nate-double-u** [comment]
(last force push rebases PR on main)

**Comment by caniszczyk** [comment]
@nate-double-u we can also link to the intro k8s course

**Comment by nate-double-u** [comment]
> @nate-double-u we can also link to the intro k8s course

Added.

**Comment by cpretzer** [comment]
This LGTM, and tagging in @PaulMichaelArmstrong for design review

**Review by cpretzer — COMMENTED** [review]
Approved by @PaulMichaelArmstrong !
🚢

**Review by cpretzer — APPROVED** [review]

**Comment by nate-double-u** [comment]
Thanks everyone!

**Comment by cpretzer** [comment]
Thank you @nate-double-u this is a really helpful detail ⭐

**Pull request merged**
