### PR TITLE
fix: design refinements

### PR DESCRIPTION
**Pull request by PatrickHeneise**

### CODE REVIEW

**Comment by PaulMichaelArmstrong** [comment]
Is the font in the community nav dropdown still bolded? It looks thick.
Screen Shot 2021-03-02 at 8 28 07 AM

Can we change the order on the community nav dropdown to:
Get Involved
Community Anchors
Linkerd Heros
Adopters
Screen Shot 2021-03-02 at 8 28 07 AM

Can we make the featured blog cards the same size whether there is one line or two for the title, like we did on the blog page?
Screen Shot 2021-03-02 at 8 29 58 AM
Screen Shot 2021-03-02 at 8 30 06 AM

Thank you!

**Comment by C-Mejlak** [comment]
@PaulMichaelArmstrong this should be sorted

**Comment by PaulMichaelArmstrong** [comment]
@wmorgan Could you review and merge?

**Comment by cpretzer** [comment]
@PaulMichaelArmstrong @C-Mejlak can you update the branch, please?

**Review by cpretzer — APPROVED** [review]
LGTM

**Pull request merged**
