### PR TITLE
feat: community heroes

### PR DESCRIPTION
**Pull request by PatrickHeneise**

### CODE REVIEW

**Comment by cpretzer** [comment]
Replaced by #909

**Comment by cpretzer** [comment]
Reopening this because @PaulMichaelArmstrong has feedback

**Comment by PaulMichaelArmstrong** [comment]
Design review: https://www.figma.com/file/T1MzgE7OlPCkhjZsl05YCtN2/Linkerd-Website?node-id=727%3A1471

/community: https://www.figma.com/file/T1MzgE7OlPCkhjZsl05YCtN2/Linkerd-Website?node-id=762%3A2738
• Updated image to just a ping with upload in Forestry
• Updated hero image max width when stacked on mobile and tablet

/linkerd-heroes: https://www.figma.com/file/T1MzgE7OlPCkhjZsl05YCtN2/Linkerd-Website?node-id=673%3A167
• Spelling error
• Hide illustration on tablet and mobile when stacked
• Updated Linkerd Hero cards
     - Updated title | location to be month and year of win
     - Removed quantity badge
• Hero cards need padding on right side of image

Thank you!

**Comment by PaulMichaelArmstrong** [comment]
Here is a PNG for the replacement image

lutz

**Pull request closed without merging**
