### PR TITLE
use a single period to avoid the enforced host check

### PR DESCRIPTION
**Pull request by lundbird**
Signed-off-by: alex lundberg <alex.lundberg@commonbond.co>

### CODE REVIEW

**Comment by lundbird** [comment]
Can we rerun the validate check? It doesnt seem to be related.

**Comment by lundbird** [comment]
I added another commit and it passes linting

**Comment by alpeb** [comment]
@lundbird can you please explain the reasoning behind this change?

**Comment by lundbird** [comment]
You explain here  https://github.com/linkerd/linkerd2/pull/4154 that the default value for enforced-host is an empty string which allows request if you port-forward. This is also the default in the values.yaml. This prevents access for us when we access the dashboard through a custom domain name.

We were able to get around this by using a single period for the regex match instead of an empty string.

**Comment by lundbird** [comment]
Nevermind I see what the confusion is about. I can add some more description to clear what this check does with an empty string and what "completely disable" means.

**Comment by cpretzer** [comment]
Thanks for the explanation @lundbird I'll keep an eye out for the changes

**Pull request closed without merging**
