### PR TITLE
add closing parenthesis to failover blog post

### PR DESCRIPTION
**Pull request by kleimkuhler**
Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

**Comment by alpeb** [comment]
Can you also please modify the helm section with this?

```
# add the linkerd-edge helm repo if you haven't already
helm repo add linkerd-edge https://helm.linkerd.io/edge
# and the linkerd-smi extension
helm repo add linkerd-smi https://linkerd.github.io/linkerd-smi
helm repo up

# install linkerd-smi and linkerd-failover
helm install linkerd-smi -n linkerd-smi --create-namespace linkerd-smi/linkerd-smi
helm install linkerd-failover -n linkerd-failover --create-namespace --devel linkerd-edge/linkerd-failover
```

**Review by cpretzer — APPROVED** [review]
🚢 👍

**Comment by alpeb** [comment]
Ok I've added my changes separately in #1323

**Comment by cpretzer** [comment]
sorry @alpeb I got click-happy with the merge button :)

**Pull request merged**
