### PR TITLE
flagger repo moved from weaveworks to fluxcd

### PR DESCRIPTION
**Pull request by brendonthiede**
The repository for flagger has been moved out of the Weaveworks org and into the "Flux project" set of repos

### CODE REVIEW

**Comment by kleimkuhler** [comment]
@brendonthiede If you can please add a DCO as described [here](https://github.com/linkerd/website/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) that will fix CI. Thanks!

**Comment by brendonthiede** [comment]
Took me some fumbling to figure out how to amend my commit, but it looks like I got it taken care of.
My journey:

1. Install [gh CLI](https://github.com/cli/cli#installation)
2. Clone my forked version of the repo: `git clone https://github.com/brendonthiede/website.git`
3. checkout the PR via gh CLI: `gh pr checkout 1020` (had to identify linkerd/website as the "base repository")
4. Amend the commit: `git commit --amend --no-edit --signoff`
5. Force the commit back in: `git push --force-with-lease origin patch-1`

Thanks for the link, Kevin!

**Review by kleimkuhler — APPROVED** [review]
Thanks @brendonthiede! Glad those steps worked out 👍

**Comment by wmorgan** [comment]
Thanks for your perseverance @brendonthiede. I think it's a real shame that what is intended to be a simple and lightweight check can turn into such a burden for contributors.

**Pull request merged**
