### PR TITLE
Update books.md

### PR DESCRIPTION
**Pull request by andreasottosson**
Wrong namespace, should be booksapp not default

### CODE REVIEW

**Comment by grampelberg** [comment]
Would you mind getting DCO to pass? https://github.com/linkerd/website/pull/265/checks?check_run_id=103944090

**Comment by andreasottosson** [comment]
#271 does the same thing, should we close this PR instead?

**Comment by andreasottosson** [comment]
I would also just like to ask if there are more errors in that last chapter of the "Books demo" page, the "Timeouts" one. Read through it and see what you think, it didn't really make sense to me. For example, just above my proposed change it reads "To edit the **books** service profile, run: ..." and then we edit the **authors** service. This was my first time trying linkerd so I might be wrong here =)

**Comment by grampelberg** [comment]
That's a great question, I'll need to do a run through, it has been awhile for me =)

**Comment by klingerf** [comment]
@andreasottosson Really sorry for the delay on this PR, and thanks for your feedback on the books app demo. I went through the timeouts section as you suggested, and it was indeed out of whack. I've submitted #319 to address that, and I'll go ahead and close out this PR.

**Pull request closed without merging**
