### PR TITLE
Avoid LoadBalancer services in demo applications

### LINKED ISSUE #716: Emojivoto demo application should not generate extra costs by default
The emojivoto demo app is referenced in the getting started guide, instructing the user to install the manifests from `run.linkerd.io` into their newly linkerd-d cluster.

These manifests contain a Service of `type: LoadBalancer`, which is handled in most cloud environments by creating a new cloud-platform LoadBalancer, which generates additional costs for the user.

I would suggest that the demo application avoid cost-generating resources, and instead create a ClusterIP service and potentially an Ingress record to be handled by the clusters existing IngressController, especially considering that the rest of the Getting Started guide instructs the user to port-forward to this service.

### PR DESCRIPTION
**Pull request by nrmitchi**
Closes #716

### CODE REVIEW

**Comment by grampelberg** [comment]
This is all generated from https://github.com/BuoyantIO/emojivoto. Would you mind doing the PR on that repo? We can move it over here then.

**Comment by grampelberg** [comment]
@nrmitchi that'd be insanely helpful if you're up for it! We'll want to update all the variants as well (daemonset, statefulset).

**Comment by grampelberg** [comment]
@nrmitchi would you mind fixing up [DCO](https://github.com/linkerd/website/pull/717/checks?check_run_id=634112974)? I can get this merged then!

**Comment by grampelberg** [comment]
Beat me to it =)

**Comment by nrmitchi** [comment]
No worries! I appreciate getting this merged in so quickly.

**Pull request merged**
