### PR TITLE
Add headless services image

### PR DESCRIPTION
**Pull request by cpretzer**
* Added thumbnail image to headless service blog post

Signed-off-by: Charles Pretzer <charles@buoyant.io>

### CODE REVIEW

**Review by wmorgan — COMMENTED** [review]
A couple things:
- If this image is from a third party, we should make sure use is permitted, and we should add some attribution on the bottom. Please copy what we've done in earlier psots.
- The image should appear somewhere in the blog post itself.
- I find this particular image kinda confusing... but I can roll with it.
- There's a lint failure introduced by a previous merge :(

Sorry to leave so many comments on a simple change.

**Comment by cpretzer** [comment]
Thanks for the comments. I'd forgotten about the image attribution.

@CathPag how do you want to move forward with this one?

**Comment by CathPag** [comment]
Ok, I tried to find something themed, and a headless statue for headless services is the best I could come up with (at least as free stock photos). We could use a screenshot of Matei's presentation. 
request in multi-cluster

**Comment by wmorgan** [comment]
I like the idea of using one of the existing diagrams. Solves all these issues at once.

**Comment by cpretzer** [comment]
> I like the idea of using one of the existing diagrams. Solves all these issues at once.

Great solve on this. Image has been updated

**Comment by CathPag** [comment]
Is this ready to be shipped?

**Comment by cpretzer** [comment]
Yep, just needs an approval.

**Review by wmorgan — APPROVED** [review]

**Pull request merged**
