### PR TITLE
Revert "Fix multicluster tutorial and kustomize resources"

### PR DESCRIPTION
**Pull request by cpretzer**
Reverts linkerd/website#1264

### CODE REVIEW

**Comment by olix0r** [comment]
Are you sure this is 2.12 specific? Nothing in the original PR seems to indicate that https://github.com/linkerd/website/pull/1264

**Review by Pothulapati — APPROVED** [review]

**Comment by cpretzer** [comment]
> Are you sure this is 2.12 specific? Nothing in the original PR seems to indicate that #1264

looking at the branch name @alpeb used, I thought it was 2.12 specific.

I'll run through the steps myself with 2.11 and confirm whether the rollback is necessary

**Comment by alpeb** [comment]
Sorry for the bad branch naming. I tested all that using stable-2.11 and the intention was indeed to be merged into `main` in order to address linkerd/linkerd2#7504. So no revert is needed.

**Comment by cpretzer** [comment]
aha! So I did the right thing :)

Thanks for confirming @alpeb

**Pull request closed without merging**
