### PR TITLE
Elkjop nordic uses Linkerd in production

### PR DESCRIPTION
**Pull request by fredrkl**
Added Elkjop nordic as a customer that uses Linkerd in production

Signed-off-by: Fredrik Klingenberg <fredrkl@gmail.com>

### CODE REVIEW

**Review by cpretzer — APPROVED** [review]
looks awesome! thanks @fredrkl

**Comment by cpretzer** [comment]
Screenshot from 2021-01-22 14-33-21

**Comment by fredrkl** [comment]
Anything you want me to do further on this @cpretzer?

**Comment by cpretzer** [comment]
thaniks for following up @fredrkl I'm just getting some changes merged in so that the checks pass. I don't need anything from you at the moment, though :smile:

**Comment by cpretzer** [comment]
the latest link checks are transient errors, so I'm just going to merge this

**Pull request merged**
