### PR TITLE
feat: add 'Linkerd Ambassadors' page

### PR DESCRIPTION
**Pull request by C-Mejlak**
Signed-off-by: Christian Mejlak <chris@mejlak.com>

### CODE REVIEW

**Comment by CathPag** [comment]
I'll work on the metadata, could you do one update on the menu like this?

1. get involved 
2. adopters
2. ambassadors
3. heroes 
4. anchors

**Comment by C-Mejlak** [comment]
Updated
- Community dropdown order of links
- description and title

**Comment by andreuxxxx** [comment]
Hello Team!

There's an update in the mockup. We did slight changes to the organization of the info on the cards and reduced the flag size. Can we use unicode for the flags?

Thanks!

https://www.figma.com/file/ugIyYepdIRIhw53wupUC4n/Linkerd-Website_July-2021?node-id=0%3A1

Codes for the flags:

https://emojipedia.org/flags/

**Comment by C-Mejlak** [comment]
- [x]  1. Update card info organization
- [x]  2. Turn flags into unicode
- [x]  3. Insert Steve's pic

All updated

**Comment by CathPag** [comment]
Looks great! I believe Steve Gray's picture had a little gray background, @C-Mejlak

**Comment by C-Mejlak** [comment]
> Looks great! I believe Steve Gray's picture had a little gray background, @C-Mejlak

You're correct didn't realize the gray wasn't part of the actual image.
Updated it now

**Comment by C-Mejlak** [comment]
Rebased @cpretzer

**Review by cpretzer — APPROVED** [review]
🚢

**Pull request merged**
