### PR TITLE
added nginx ingress example to use var  Signed-off-by: Jeff Puccinell…

### PR DESCRIPTION
**Pull request by poochwashere**
…i <lamemail@gmail.com>

Fixes: https://github.com/linkerd/website/issues/510

Adds a `Nginx` example that illustrates how to template the port number to support multiple services using different port numbers behind a single ingress.

### CODE REVIEW

**Comment by poochwashere** [comment]
hmmm, for the `dco` i cannot make that "action required" go away. 

I attempted this: 
`git commit --amend --signoff`
`git push --force-with-lease origin master`

Is there a step that I may be missing?

**Comment by ihcsim** [comment]
@poochwashere Looks like there is still one commit that isn't passing the DCO check. I think the simplest approach is just to squash your branch, and re-push it. So something like:
```
$ git reset --soft 1a6797cec # I believe this is your first commit 
$ git commit --am # update commit message, make sure it's signed etc.
$ git push -f
```

**Comment by poochwashere** [comment]
I think that I am getting closer, failed the CI test now for some reason though. ```ERROR 2019/09/16 21:23:14 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1141107658440753152&dnt=false": Failed to retrieve remote file: Forbidden
Total in 948 ms
Error: Error building site: logged 1 error(s)
Makefile:103: recipe for target 'build-linkerd.io' failed
make: *** [build-linkerd.io] Error 255
Exited with code 2```

**Comment by grampelberg** [comment]
Don't worry about that one, the link checker is a little aggressive to make sure dead links don't crop up over time. Thanks!

**Pull request merged**
