### PR TITLE
New directory for 2.13 docs

### PR DESCRIPTION
**Pull request by alpeb**
As instructed in the internal `linkerd-docs` procedure.

### CODE REVIEW

**Comment by kflynn** [comment]
@alpeb Is this just `cp 2-edge 2.13`?

**Review by adleong — APPROVED** [review]

**Review by kflynn — APPROVED** [review]
Looks great, hit it! 🙂

**Comment by alpeb** [comment]
> @alpeb Is this just `cp 2-edge 2.13`?

Unfortunately it's not just that, but we also require a bunch of other small changes in other places.

**Comment by kflynn** [comment]
I should've phrased that better: yeah, there are metadata changes, but it seems that the content of the docs is what was on 2-edge.

**Comment by alpeb** [comment]
> I should've phrased that better: yeah, there are metadata changes, but it seems that the content of the docs is what was on 2-edge.

Correct

**Pull request merged**
