### PR TITLE
#674 Blog RSS feed

### PR DESCRIPTION
**Pull request by shokohsc**
Added rss link in header html tag

Signed-off-by: Dimitri Pommier shokohsc@gmail.com

### CODE REVIEW

**Comment by grampelberg** [comment]
@cpretzer does this work for you?

**Comment by shokohsc** [comment]
I think I added too many pages to the rss feed...

**Comment by shokohsc** [comment]
I cannot seem to target only /blog/ uri to generate the rss meta tag...
I cannot pass the tests locally though Oo probably have to do with running hugo inside a container.

**Comment by cpretzer** [comment]
@shokohsc this didn't work for me locally, and that is partially because I'm using hugo `0.55.5` and the [template](https://github.com/gohugoio/hugo/blob/v0.55.5/tpl/tplimpl/embedded/templates/_default/rss.xml) for that version is different than that which is linked in the hugo rss docs.

When I use the template for `0.55.5`, there are no compile errors, but the RSS doesn't render in the `<head>` tag.

If the tests aren't passing in your local environment, then that's the first place to start. Get those passing and you may have to change your hugo version.

Once everything works locally, please be sure to commit your changes with a [DCO](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md#certificate-of-origin) so that we know you are signing the commit.

**Comment by shokohsc** [comment]
I removed the rss limit that I intended to put in the first place.
I also squashed my multiple commits.

Removing the rss limit configuration allowed to pass tests but I cannot seem to pass the html generated html validation, netlify or locally.

Locally (still from within a container exposing 1313 & 443 ports) it seems to not be able to connect via ssl to s7.addthis.com domain when I type make check link:
````
root@db3391f6bcc8:/website# make check lint
make[1]: Entering directory '/website'
cp -R *linkerd.io tmp/
for fname in $(grep -rnl 'L5D2_STABLE_VERSION' tmp); do \
	sed -i.bak 's/L5D2_STABLE_VERSION/stable-2.8.0/g' $fname; \
	rm $fname.bak; \
done
for fname in $(grep -rnl 'L5D2_EDGE_VERSION' tmp); do \
	sed -i.bak 's/L5D2_EDGE_VERSION/edge-20.6.2/g' $fname; \
	rm $fname.bak; \
done
make[1]: Leaving directory '/website'
cd tmp/linkerd.io && ./build
Building sites … WARN 2020/06/18 11:15:01 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url

                   | EN
+------------------+-----+
  Pages            | 273
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 548
  Processed images |   0
  Aliases          | 262
  Sitemaps         |   1
  Cleaned          |   0

Total in 38652 ms
cd tmp/linkerd.io && htmltest
htmltest started at 11:15:27 on public
========================================================================
running in concurrent mode, this is experimental
2017/03/08/linkerd-one-hundred-billion-production-requests/index.html
  Get https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c6c43959addf02a: dial tcp 0.0.0.0:443: connect: connection refused --- 2017/03/08/linkerd-one-hundred-billion-production-requests/index.html --> //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c6c43959addf02a
2017/04/25/announcing-linkerd-1-0/index.html
  Get https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c6c43959addf02a: dial tcp 0.0.0.0:443: connect: connection refused --- 2017/04/25/announcing-linkerd-1-0/index.html --> //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c6c43959addf02a
...
...
...
2016/12/10/slow-cooker-load-testing-for-tough-software/index.html
  Get https://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c6c43959addf02a: dial tcp 0.0.0.0:443: connect: connection refused --- 2016/12/10/slow-cooker-load-testing-for-tough-software/index.html --> //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c6c43959addf02a
community/index.html
  Get https://fr.ask.com/?o=0&l=dir&ad=dirN: dial tcp 0.0.0.0:443: connect: connection refused --- community/index.html --> https://ask.com/
========================================================================
✘✘✘ failed in 11.4634995s
98 errors in 444 documents
Makefile:78: recipe for target 'check' failed
make: *** [check] Error 1
````
Thought those links were dead but they obviously aren't, i.e: https://linkerd.io/2016/12/10/slow-cooker-load-testing-for-tough-software/index.html

@cpretzer @grampelberg Any idea ?

**Comment by cpretzer** [comment]
@shokohsc it looks like the latest errors are due to branch renaming. The URL referenced in 

`https://github.com/shokohsc/website/blob/master/linkerd.io/content/1/tutorials/part-one.md`
and
`https://github.com/shokohsc/website/blob/master/linkerd.io/content/blog/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics.md`

should be changed to  `https://raw.githubusercontent.com/linkerd/linkerd-viz/main/k8s/linkerd-viz.yml`

**Comment by shokohsc** [comment]
Ok, thanks, after rebasing off 'main' branch, it actually passes but not locally, do you have any clue about that ?
````
...dial tcp 0.0.0.0:443: connect: connection refused...
````
Still running in a golang:latest container exposing both 8080 & 443 ports and binding hugo to 0.0.0.0 interface.

**Comment by grampelberg** [comment]
Hugo defaults to 1313 I believe.

**Comment by shokohsc** [comment]
My bad, was looking at another container ports, I exposed the right ports, well I hope so: 

````
db3391f6bcc8 hugo "docker-entrypoint.s…" 5 days ago Up 5 days 0.0.0.0:443->443/tcp, 0.0.0.0:1313->1313/tcp hugo
````

I'll look on my own, this has nothing to do with this pull request as the command: make check lint exits ok (0) on netlify.
Thanks anyway.

**Pull request merged**
