### PR TITLE
rework for annotations from yaml

### PR DESCRIPTION
**Pull request by StupidScience**
Fixes https://github.com/linkerd/linkerd2/issues/3501

PR for `linkerd doc` command - https://github.com/linkerd/linkerd2/pull/3564
I believe that this one should be merged after it.

### CODE REVIEW

**Comment by ihcsim** [comment]
@StupidScience Thanks for this PR. Can we retain the sort order of the annotations table? The following diff should do it. Thanks!

```diff
diff --git a/linkerd.io/layouts/shortcodes/cli/annotations.html b/linkerd.io/layouts/shortcodes/cli/annotations.html
index 6cd9cf1..7970fa0 100644
--- a/linkerd.io/layouts/shortcodes/cli/annotations.html
+++ b/linkerd.io/layouts/shortcodes/cli/annotations.html
@@ -11,7 +11,7 @@
       </tr>
     </thead>
     <tbody>
-      {{ range site.Data.cli.AnnotationsReference }}
+      {{ range sort site.Data.cli.AnnotationsReference "Name" }}
       {{ partial "cli/annotations" . }}
       {{ end }}
     </tbody>
```

**Comment by StupidScience** [comment]
@ihcsim in this case annotations with `config.alpha.linkerd.io` prefix appear on top of table. Is it ok? What behaviour with other prefixes is expected?

**Comment by ihcsim** [comment]
@StupidScience Yup, that's fine. The `config.alpha.linkerd.io/trace-collector-service-account` is a stop-gap; we might eventually remove it.

**Comment by StupidScience** [comment]
@ihcsim updated according to your comment

**Pull request merged**
