### PR TITLE
fix: update tap certificate commonName and dnsName

### PR DESCRIPTION
**Pull request by haithem-souala**
Fix commonName and dnsName in  _Automatically Rotating Webhook TLS Credentials_ certificate for tap and tap-injector

### CODE REVIEW

**Review by kleimkuhler — APPROVED** [review]
Thanks @haithem-souala

**Comment by kleimkuhler** [comment]
@haithem-souala Could you please merge in the latest `master`? I think it might fix this CI check that is failing.

**Comment by haithem-souala** [comment]
Indeed.

**Comment by kleimkuhler** [comment]
Thanks!

**Pull request merged**
