### PR TITLE
Fix getting-started index.md typo

### PR DESCRIPTION
**Pull request by HomayoonAlimohammadi**
In the getting-started `_index.md` there was a typo which I noticed and fixed.

### CODE REVIEW

**Comment by HomayoonAlimohammadi** [comment]
It will be amazing if you would take a look at this PR. Thanks! @travisbeckham @wmorgan @kflynn

**Review by kflynn — APPROVED** [review]
🤦‍♂️ Thanks!!

**Comment by kflynn** [comment]
@HomayoonAlimohammadi Appreciate it! We need you to agree to the [DCO](https://github.com/linkerd/linkerd2-proxy/blob/main/DCO) – you can either do that by force-pushing an amended commit, or by just telling us in a comment here that you're good with it. Many thanks!! 🙂

**Comment by wmorgan** [comment]
We can skip the DCO for this change. See https://github.com/linkerd/linkerd2/blob/main/CONTRIBUTING.md#option-3-very-simple-changes

**Comment by kflynn** [comment]
Ah right -- thanks @wmorgan! Landing this one. 🙂

**Pull request merged**
